#!/usr/bin/env python

import argparse
from utils import pull_wish_list


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='convert amz wish list to goodreads import format')
    parser.add_argument('--url', dest='url', type=str, required=True)
    args = parser.parse_args()

    print(args.url)
